name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package
      env:
        ACTIONS_STEP_DEBUG: true
        DB_URL: ${{ secrets.DB_URL }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    - name: List target directory
      run: ls -al target/
    - name: Verify AWS CLI
      run: aws --version
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Upload to S3
      run: |
        jar_file=$(ls target/*.jar | head -n 1)
        aws s3 cp "$jar_file" s3://elasticbeanstalk-us-east-1-339712862508/
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy to Elastic Beanstalk
      env:
        APPLICATION_NAME: fesprin
        ENVIRONMENT_NAME: Fesprin-env
        S3_BUCKET: elasticbeanstalk-us-east-1-339712862508
      run: |
        jar_file=$(aws s3 ls s3://elasticbeanstalk-us-east-1-339712862508/ | sort | tail -n 1 | awk '{print $4}')
        version_label="${GITHUB_SHA}-$(date +%s)"  # Add a timestamp to make it unique
        aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $version_label --source-bundle S3Bucket=$S3_BUCKET,S3Key=$jar_file
        aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $version_label

