name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package
      env:
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        DB_URL: ${{ secrets.DB_URL }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    - name: Upload to S3
      run: |
        # Ensure that the file exists
        ls target/
        # Upload the jar file to the S3 bucket
        aws s3 cp target/*.jar s3://elasticbeanstalk-us-east-1-339712862508/
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy to Elastic Beanstalk
      env:
        APPLICATION_NAME: fesprin
        ENVIRONMENT_NAME: Fesprin-env
        S3_BUCKET: elasticbeanstalk-us-east-1-339712862508
      run: |
        jar_file=$(aws s3 ls s3://elasticbeanstalk-us-east-1-339712862508/ | sort | tail -n 1 | awk '{print $4}')
        aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=$S3_BUCKET,S3Key=$jar_file
        aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA
